<h2>View index</h2>

<?php if(isset($this->posts) && count($this->posts)): ?>

<table>
    <?php for($i=0; $i < count($this->posts); $i++): ?>
    <tr>
        <td><?php echo $this->posts[$i]['id']; ?></td>
        <td><?php echo $this->posts[$i]['title']; ?></td>
        <td><?php echo $this->posts[$i]['post']; ?></td>
    </tr>
    <?php endfor; ?>
</table>
<?php else: ?>

<p><strong>Nejsou žádné posty</strong></p>

<?php endif; ?>

<p><a href="<?php BASE_URL; ?>post/add">Přidat článek</a></p>