<h2>Register</h2>
<form name="form1" method="post" action="">
    <input type="hidden" value="1" name="enviar"/>
    <p>
        <label>Name:</label>
        <input type="text" name="name" value="<?php if(isset($this->data)) echo $this->data['name']; ?>"/>
    </p>
    <p>
        <label>User:</label>
        <input type="text" name="user" value="<?php if(isset($this->data)) echo $this->data['user']; ?>"/>
    </p>
    <p>
        <label>Email:</label>
        <input type="text" name="email" value="<?php if(isset($this->data)) echo $this->data['email']; ?>"/>
    </p>
    <p>
        <label>Password:</label>
        <input type="password" name="pass"/>
    </p>
    <p>
        <label>Confirm:</label>
        <input type="password" name="confirm"/>
    </p>
    <p>
        <input type="submit" value="enviar"/>
    </p>
</form>